
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoryblokContextProvider } from "./lib/StoryblokContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ApiBlok",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-white text-gray-900 font-sans ${geistSans.variable} ${geistMono.variable}`}>
        <StoryblokContextProvider>
        {children}
        </StoryblokContextProvider>
      </body>
    </html>
  );
}
