// lib/mockData.js
export const apis = [
  {
    id: 1,
    name: "Stripe Payment Intent",
    method: "POST",
    difficulty: "Easy",
    category: "Payments",
    description: "Create and manage payment intents for processing payments",
    endpoint: "/v1/payment_intents",
    authRequired: true,
    commonUses: ["Create payment", "Capture payment", "Cancel payment"],
  },
  {
    id: 2,
    name: "PayPal Orders API",
    method: "POST",
    difficulty: "Medium",
    category: "Payments",
    description: "Create and manage PayPal orders for checkout flow",
    endpoint: "/v2/checkout/orders",
    authRequired: true,
    commonUses: ["Create order", "Capture order", "Refund order"],
  },
  {
    id: 3,
    name: "Twilio SMS API",
    method: "POST",
    difficulty: "Easy",
    category: "Messaging",
    description: "Send and manage SMS messages using Twilio",
    endpoint: "/v1/messages",
    authRequired: true,
    commonUses: ["Send SMS", "Check delivery status"],
  },
  {
    id: 4,
    name: "Auth0 Login API",
    method: "POST",
    difficulty: "Medium",
    category: "Auth",
    description: "Authenticate users and manage login sessions with Auth0",
    endpoint: "/oauth/token",
    authRequired: false,
    commonUses: ["Login user", "Refresh token"],
  },
];
